dataset:
  fixed_image_shape:
  - 284
  - 120
  - 64
  moving_image_shape:
  - 284
  - 120
  - 64
  moving_label_shape:
  - 200
  - 3
  fixed_label_shape:
  - 200
  - 3
  test:
    dir:
      - "/data3/prj_register/ALv3/test/nonaugmented/2023-01-16-15"
      - "/data3/prj_register/ALv3/test/nonaugmented/2023-01-16-22"
      - "/data3/prj_register/ALv3/test/nonaugmented/2023-01-17-07"
      - "/data3/prj_register/ALv3/test/nonaugmented/2023-01-17-14"
      - "/data3/prj_register/ALv3/test/nonaugmented/2023-01-18-01"
    format: "h5"
    labeled: false
  train:
    dir:
      - "/data3/prj_register/ALv3/train/nonaugmented/2022-01-17-01"
      - "/data3/prj_register/ALv3/train/nonaugmented/2023-07-28-04"
      - "/data3/prj_register/ALv3/train/nonaugmented/2023-08-19-08"
      - "/data3/prj_register/ALv3/train/nonaugmented/2023-01-06-01"
      - "/data3/prj_register/ALv3/train/nonaugmented/2023-01-19-22"
      - "/data3/prj_register/ALv3/train/nonaugmented/2023-08-18-11"
      - "/data3/prj_register/ALv3/train/nonaugmented/2023-01-05-18"
      - "/data3/prj_register/ALv3/train/nonaugmented/2023-06-24-11"
      - "/data3/prj_register/ALv3/train/nonaugmented/2022-12-21-06"
      - "/data3/prj_register/ALv3/train/nonaugmented/2023-01-05-01"
      - "/data3/prj_register/ALv3/train/nonaugmented/2022-07-26-01"
      - "/data3/prj_register/ALv3/train/nonaugmented/2023-07-11-10"
      - "/data3/prj_register/ALv3/train/nonaugmented/2023-08-22-08"
      - "/data3/prj_register/ALv3/train/nonaugmented/2022-06-28-07"
      - "/data3/prj_register/ALv3/train/nonaugmented/2023-06-24-02"
      - "/data3/prj_register/ALv3/train/nonaugmented/2022-06-14-07"
      - "/data3/prj_register/ALv3/train/nonaugmented/2023-01-09-28"
      - "/data3/prj_register/ALv3/train/nonaugmented/2023-06-09-01"
      - "/data3/prj_register/ALv3/train/nonaugmented/2022-02-08-04"
      - "/data3/prj_register/ALv3/train/nonaugmented/2023-03-07-01"
      - "/data3/prj_register/ALv3/train/nonaugmented/2023-01-17-01"
      - "/data3/prj_register/ALv3/train/nonaugmented/2023-08-25-02"
      - "/data3/prj_register/ALv3/train/nonaugmented/2023-01-23-21"
      - "/data3/prj_register/ALv3/train/nonaugmented/2022-06-14-13"
      - "/data3/prj_register/ALv3/train/nonaugmented/2022-07-20-01"
      - "/data3/prj_register/ALv3/train/nonaugmented/2022-02-16-01"
      - "/data3/prj_register/ALv3/train/nonaugmented/2023-07-01-09"
      - "/data3/prj_register/ALv3/train/nonaugmented/2023-01-23-08"
      - "/data3/prj_register/ALv3/train/nonaugmented/2023-07-01-01"
      - "/data3/prj_register/ALv3/train/nonaugmented/2023-07-07-11"
      - "/data3/prj_register/ALv3/train/nonaugmented/2023-07-11-02"
      - "/data3/prj_register/ALv3/train/nonaugmented/2022-08-02-01"
      - "/data3/prj_register/ALv3/train/nonaugmented/2023-06-24-28"
      - "/data3/prj_register/ALv3/train/nonaugmented/2023-06-09-10"
      - "/data3/prj_register/ALv3/train/nonaugmented/2023-09-15-08"
      - "/data3/prj_register/ALv3/train/nonaugmented/2023-08-07-01"
      - "/data3/prj_register/ALv3/train/nonaugmented/2023-01-19-08"
      - "/data3/prj_register/ALv3/train/nonaugmented/2022-03-15-04"
      - "/data3/prj_register/ALv3/train/nonaugmented/2022-06-28-01"
      - "/data3/prj_register/ALv3/train/nonaugmented/2023-08-17-08"
      - "/data3/prj_register/ALv3/train/nonaugmented/2022-02-16-04"
      - "/data3/prj_register/ALv3/train/nonaugmented/2023-07-07-01"
      - "/data3/prj_register/ALv3/train/nonaugmented/2023-08-07-16"
      - "/data3/prj_register/ALv3/train/nonaugmented/2023-01-23-01"
      - "/data3/prj_register/ALv3/train/nonaugmented/2022-07-15-06"
      - "/data3/prj_register/ALv3/train/nonaugmented/2022-03-22-01"
      - "/data3/prj_register/ALv3/train/nonaugmented/2022-06-14-01"
      - "/data3/prj_register/ALv3/train/nonaugmented/2023-07-07-18"
      - "/data3/prj_register/ALv3/train/nonaugmented/2023-07-06-01"
      - "/data3/prj_register/ALv3/train/nonaugmented/2023-01-19-15"
      - "/data3/prj_register/ALv3/train/nonaugmented/2022-04-18-04"
      - "/data3/prj_register/ALv3/train/nonaugmented/2022-07-15-12"
      - "/data3/prj_register/ALv3/train/nonaugmented/2023-01-23-15"
      - "/data3/prj_register/ALv3/train/nonaugmented/2023-07-13-01"
      - "/data3/prj_register/ALv3/train/nonaugmented/2023-08-17-01"
      - "/data3/prj_register/ALv3/train/nonaugmented/2023-07-12-01"
      - "/data3/prj_register/ALv3/train/nonaugmented/2023-01-19-01"
    format: "h5"
    labeled: true
  type: paired
  valid:
    dir:
      - "/data3/prj_register/ALv3/valid/nonaugmented/2023-09-02-10"
      - "/data3/prj_register/ALv3/valid/nonaugmented/2022-04-12-04"
      - "/data3/prj_register/ALv3/valid/nonaugmented/2023-01-16-08"
      - "/data3/prj_register/ALv3/valid/nonaugmented/2023-01-06-15"
      - "/data3/prj_register/ALv3/valid/nonaugmented/2023-08-23-23"
      - "/data3/prj_register/ALv3/valid/nonaugmented/2023-01-09-22"
      - "/data3/prj_register/ALv3/valid/nonaugmented/2023-01-16-01"
      - "/data3/prj_register/ALv3/valid/nonaugmented/2023-01-06-08"
      - "/data3/prj_register/ALv3/valid/nonaugmented/2023-08-18-18"
      - "/data3/prj_register/ALv3/valid/nonaugmented/2023-08-22-01"
      - "/data3/prj_register/ALv3/valid/nonaugmented/2023-01-09-15"
      - "/data3/prj_register/ALv3/valid/nonaugmented/2023-10-15-18"
      - "/data3/prj_register/ALv3/valid/nonaugmented/2023-01-10-07"
      - "/data3/prj_register/ALv3/valid/nonaugmented/2023-01-10-14"
      - "/data3/prj_register/ALv3/valid/nonaugmented/2023-01-13-07"
      - "/data3/prj_register/ALv3/valid/nonaugmented/2023-10-03-02"
      - "/data3/prj_register/ALv3/valid/nonaugmented/2022-04-05-01"
      - "/data3/prj_register/ALv3/valid/nonaugmented/2023-07-01-23"
      - "/data3/prj_register/ALv3/valid/nonaugmented/2023-06-24-19"
      - "/data3/prj_register/ALv3/valid/nonaugmented/2023-09-15-01"
      - "/data3/prj_register/ALv3/valid/nonaugmented/2023-01-09-08"
      - "/data3/prj_register/ALv3/valid/nonaugmented/2023-08-31-03"
    format: "h5"
    labeled: true
    sample_label: "all"
train:
  backbone:
    extract_levels:
    - 0
    - 1
    - 2
    - 3
    name: "local"
    num_channel_initial: 16
  epochs: 1000
  loss:
    image:
      kernel_size: 16
      name: "lncc"
      weight: 1
    label:
      name: "centroid"
      weight: 0.1
    regularization:
      hybrid: true
      img_size:
      - 284
      - 120
      - 64
      name: "hybrid"
      weight: 1
      hybrid_weight:
        "axisdiff": 0.005
        "gradient": 0.0
        "nonrigid": 0.05
        "diff": 0.0
  method: "ddf"
  optimizer:
    learning_rate: 0.0001
    name: "Adam"
  preprocess:
    batch_size: 4
    data_augmentation:
      name: "centroid_affine"
      moving_label_size: 
        - 200
        - 3
      fixed_label_size:
        - 200
        - 3
    num_parallel_calls: -1
    shuffle_buffer_num_batch: 4
  save_period: 1
  single_channel: True
